spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loja-microservice?useTimezone=true&serverTimezone=UTC
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
